### ISSUE TITLE
multiple copies

### ISSUE THREAD

**Issue by zxfrank** [xseignard/thermalPrinter#13]
Hello, is there an existing method to print multiple copies? or I must call .print X times?

thanks

**Comment by xseignard** [comment]
Hello,
Right now there is not, but it should be an easy feature to add.

Would you like to take care of it?

**Comment by zxfrank** [comment]
why not! I'm on it

**Comment by xseignard** [comment]
Great! Looing forward to it!

**Comment by zxfrank** [comment]
actually I send each copy individually because I want "Copy x/y" to be printed. Here's my code for those interested:

//this snippet has not been tested, I stripped some parts because some variables are related to my app which out of its context means absolutely nothing

var nbCopies=2; //to print 2x
function print(data,copy,cback){
    var printedTimer;
    var p=new Printer(...);
     //put your printing code here
   p.printLine('Copy #'+copy+'/'+nbCopies)
   .print(function() {
	clearTimeout(printedTimer);
	printedTimer=setTimeout(function(){ //the event got fired each time you send a command so i catch it and the last time it gets fired, I call my callback function
        cback({result:'printed'});
        },300);
}

//then you call the function
print(mydata,1,function(res){
     for(var i=2;i<=nbCopies;i++){
	(function(i){ //to get my increment inside the settimeout
		setTimeout(function(){ //allow previous print to print ;)
          		print(mydata,i,function(res){
                		console.log('Copy '+i+' has been printed');
          		});
          	},200*i);
	})(i);
     }
})

**Comment by xseignard** [comment]
zxfrank, I don't understand your code :)

I think something like this should work out of the box:

```js
var printer = new Printer(serialPort);
printer.on('ready', function() {
  for (var i=0; i<=nbCopies; i++){
    printer.printLine('Copy #' + i + '/' + nbCopies);
  }
  printer.print(function() { console.log('done'); });
```

**Comment by zxfrank** [comment]
Ok so if you want to print 2x the same check (eg for a restaurant) 1 for the cashier, 1 for the customer, you can use my function

if you want to print 2 lines containing
```
Copy 1/2
Copy 2/2
```
you can use your function

**Comment by xseignard** [comment]
With my solution you can do both.

**Comment by zxfrank** [comment]
You're right, I haven't seen it that way...

**Comment by xseignard** [comment]
@zxfrank nothing is sent to the printer until you call `printer.print(function(){ });`. It's the concept of fluent interface.

Internally, commands are stored in an array and then sent in series to the printer when `print` is called. It means that you can prepare the whole stuff you need to be printed and then actually print it.

I guess I can close the issue?

Let me know if you have more questions.

Regards
