### ISSUE TITLE
Printing on windows

### ISSUE THREAD

**Issue by smanaqvi83** [xseignard/thermalPrinter#14]
Hi, 
I want to use this library for printing the receipts. But I am unable to do this. whenever I use 'new SerialPort('/dev/ttyUSB0',  or new SerialPort('USB001'), or any other serial port it gives me error that the port file wasn't found. 
So please help me regarding this issue. 

Thanks.

**Comment by xseignard** [comment]
On windows ports are something like `COM3` or `COM4` or `COMXX` where `XX` is a number.

**Comment by xseignard** [comment]
Hi @smanaqvi83 any updates?

**Comment by smanaqvi83** [comment]
If there is any new build haven't tried it yet. But with the previous
versions I'm still unable to open connection via COM ports.

**Comment by xseignard** [comment]
Hello,
And are you able to use `serialport`  without `thermalprinter` to open a serial connection?

**Comment by smanaqvi83** [comment]
No. Not at all.
But to print from thermal printer we used this library
https://www.npmjs.com/package/printer

And used the codes from thermal-printer for the formatting of print
document.

Regards
Ali

**Comment by xseignard** [comment]
Could you explain à little more

**Comment by smanaqvi83** [comment]
Sure.
Just give me some time. I'll get back to you in a day max.

Regards

**Comment by xseignard** [comment]
Great!
Thanks :)

**Comment by smanaqvi83** [comment]
Hi
Sorry for the delay.
In thermal-node-printer there is a method for printing the document.
Now we just replaced node-thermal-printer "Print" code I think the name of
method there is "execute" with the node-printer "PrintDirect" method.
Thats it. And we can set the formatting using thermal printer and then call
the print method which will print the document.
But so far we haven't got the solution related to image.

"This is the sample code"
execute: function (printer_name) {
        //console.log("Kitchen in Execute : " + str);
        printText = printText.replace(/š/g, 's');
        printText = printText.replace(/Š/g, 'S');
        printText = printText.replace(/č/g, 'c');
        printText = printText.replace(/Č/g, 'C');
        printText = printText.replace(/ć/g, 'c');
        printText = printText.replace(/Ć/g, 'c');
        printText = printText.replace(/ž/g, 'z');
        printText = printText.replace(/Ž/g, 'Z');
        //console.log("Print Text : " + printText);
        var printerName = printer_name;
        printer.printDirect({
            data: printText
            , printer: printer_name
            , type: "RAW"
            , success: function (jobId) {
                //console.log("Hurray....." + printerName);
                var job = printer.getJob("CITIZEN CT-S601", jobId);
                 console.log("Job : " + JSON.stringify(job, null, 4));
            }
            , error: function (err) { console.log(err); }
        });

        //writeFile('/dev/usb/lp0', printText, function (err) {
        //    if (err) {
        //        console.log('Print failed', err);
        //    } else {
        //        console.log('Print done');
        //        printText = "";
        //    }
        //});
    }

Feel free to contact in case of any issue.

Regards
Ali.

**Comment by xseignard** [comment]
Thanks Ali,
From what I see you use a printer called `CITIZEN CT-S601` right?

If so, this lib is not intended to work with such printers. Maybe I could check with @Klemen1337 to see if they need help with image printing on their lib.

I keep you updated

**Comment by smanaqvi83** [comment]
Yes right. But this printer is thermal printer.

**Comment by xseignard** [comment]
Yes but this lib is intended to work with adafruit thermal printer only

**Comment by smanaqvi83** [comment]
No idea about that.

**Comment by Klemen1337** [comment]
@xseignard yes, we would love some help with image printing. If you have any ideas how to do it please fork the library :smile:
