### ISSUE TITLE
Any options without the usb adapter?

### ISSUE THREAD

**Issue by zettam** [xseignard/thermalPrinter#15]
Would love to know if there are any options to run the printer without the usb module. There is a video I came across that does that by using python, here it is:
https://www.youtube.com/watch?v=TC9V7cotUgw

Would love to know. Thank you.

**Comment by xseignard** [comment]
Sure it will work on a Raspberry Pi, just use the UART pins of the Pi. And declare the printer like this:

```js
var SerialPort = require('serialport').SerialPort,
    serialPort = new SerialPort('/dev/ttyAMA0', {
        baudrate: 19200
    }),
    Printer = require('thermalprinter');
```

It should work.

Let me know

**Comment by zettam** [comment]
Thanks! Waiting for my printer to arrive, will try asap!

**Comment by zettam** [comment]
it works -- however I have other issues now (like image printing being utterly slow)

**Comment by xseignard** [comment]
I cose this issue since it work. I'm working on other issues.
