### ISSUE TITLE
Set bold on inline text (without line break)

### ISSUE THREAD

**Issue by drskullster** [xseignard/thermalPrinter#20]
Hi Xavier,

I'm having trouble seeing how I could push the bold command on a set of characters rather than a whole line.

For now the API doesn't seem to permit it :
```javascript
printer
    .printLine('example text ')
    .bold(true)
    .printLine('takes a new line')
    .bold(false)
    .print();
```

I wrote a new method called `printText()` on [my fork](https://github.com/3000d/thermalPrinter/commit/8b2623bef75995c513933b8e79bdb46c8a4fa5a9). It's essentially the old `printLine()` method without the line break command (10). The new `printLine()` method calls `printText()` and adds the line break. Thing is, I have to explicitly add a line break, otherwise it won't print anything :

```javascript
printer
    .printText('this is ')
    .bold(true)
    .printText('on the same ')
    .bold(false)
    .printText('line')
    .printLine('') // this is ugly, but it won't print without it.
    .print();
```

So what can we do ? One way I see is a check in the `print()` method. If last command is not 10, then add it. But I'm not sure it's a good idea, and anyway I'm not confortable enough with Serial and Buffer to write something like that.

What do you think ?

**Comment by xseignard** [comment]
Hello again @drskullster 

Yes that's a missing thing in the lib! Good catch!

I'll investigate on that and provide a solution ASAP.

Regards

**Comment by xseignard** [comment]
Re,
Please have a look at https://github.com/xseignard/thermalPrinter/commit/f669056 and tell me if it suits you?

Regards

**Comment by drskullster** [comment]
Hi there,

Thanks for the commit !

Adding a second argument to `printLine()` was also my first thought, but the name of the method can be confusing when you just want to print some characters IMHO. And this doesn't solve the problem that you still have to add a `printLine()` at the end, or it won't print.

The least confusing API I can think of is this :
```javascript
printer
    .addText('some ')
    .addText('text ')
    .addText('on the same line.')
    .printLine();
```

Which could also be written like that :
```javascript
printer
    .addText('some ')
    .addText('text ')
    .printLine('on the same line.');
```

It's basically what I proposed [here](https://github.com/3000d/thermalPrinter/commit/8b2623bef75995c513933b8e79bdb46c8a4fa5a9) (moving `printLine()` logic to a `printText()` method without the line break, and calling `printText()` in `printLine()` with a line break) but instead of naming the method `printText()`, we would name it `addText()` so that we understand quickly that it doesn't print on its own.

What do you think ?

**Comment by xseignard** [comment]
Hello @drskullster,

I get your point, I have one more idea, I check it ASAP and come back to you with a new version published to npm tomorrow.

Thanks for sharing your points, I appreciate that.

Regards

Xavier

**Comment by soupman99** [comment]
+1 thanks for this.  I would love to set left() and right() within the same line.  Seems like this update would solve my problem too.

**Comment by xseignard** [comment]
Hi @soupman99

Yes sûre this would enable yournreq

**Comment by xseignard** [comment]
Hello @soupman99

Sure this would enable your request.

In plan to do it today, and I'll come back to you with an example.

Regards,

Xavier

**Comment by drskullster** [comment]
@soupman99 I just tested on my fork and it doesn't work. @xseignard would have a better understanding than me, but I think that's up to the firmware and it doesn't seem to permit it.

One easy way to do it would be to calculate the spaces manually, since there's a fixed number of characters per line (32 I think) :
```javascript
var printLeftAndRight = function(printer, leftText, rightText) {
  var lineChars = 32;
  var leftChars = leftText.length;
  var rightChars = rightText.length;
  var spacesCount = lineChars - rightChars - leftChars;
  var spaces = Array(spacesCount + 1).join(' ');

  if(leftChars + rightChars > lineChars) {
    throw new Error('You\'re trying to print left and right with too much characters (max '+ lineChars + ')');
  }

  return printer.printLine(leftText + spaces + rightText);
};
```

It's not perfect since it doesn't take indent or large types into account. But it does the job :)

**Comment by soupman99** [comment]
@drskullster thanks for the snippet.  This is a good work around.

**Comment by xseignard** [comment]
@drskullster @soupman99 not tested yet, I take some time this evening to tackle this.

Thanks to both for your valuable inputs.

Regards

**Comment by xseignard** [comment]
Hello guys, so after a quick check it seems it is a firmware limitation, or something I missread in the datasheet (available here: https://www.adafruit.com/datasheets/A2-user%20manual.pdf)
So the @drskullster trick seems the way to go @soupman99, smart catch @drskullster 

I published `v0.3.8` to npm. This version integrates the fix for this issue, and the #19 PR

Thanks for your inputs, 

I hope you have fun using it, let me know what you're doing with it.

Regards,

Xavier

**Comment by soupman99** [comment]
@xseignard thanks for the update.

**Comment by drskullster** [comment]
@xseignard thanks for your work on this and the merge on #19.

@soupman99 glad I could help.

I'm using the printer a a "story dispenser" : it's available in a place where people are waiting. When a button is pushed, it prints a random story or comic that you can read while waiting. The server is a Nodejs Application on a Raspberry Pi with several features to come like parsing a markdown formatted text to serve the printer, format text with linebreaks and hyphens, and a web interface to test this directly with web sockets. 

Code is available here : https://github.com/3000d/aleastory-server

Regards
