### ISSUE TITLE
Printing images

### ISSUE THREAD

**Issue by clem91** [xseignard/thermalPrinter#24]
HI,

The librarie works really great with text but when I try to print images, i have some troubles. 
Everytime I want to print an image, the begining is quite good but at a certain moment, the printer is going mad and print some unreadable characters mostly chinese symbols.
My printer is an adafruit mini thermal printer connected with usb by a usb/serial converter. I tried lot of things  but unfortunatly with no success.  

![Image of Yaktocat](https://image.noelshack.com/fichiers/2017/04/1485195307-20170123-185745.jpg)

**Comment by xseignard** [comment]
Salut @clem91 !

Could you please share you whole code?

Also, what's the power supply you're using?

Regards

**Comment by clem91** [comment]
Thanks for your response @xseignard
All the used codes look like the demo.js code really simply just for testing. In fact with the demo.js, I print the node logo but the robot is pretty bad (not ended well with bottom cropped and the corners are not rounded).  The power supply is a USB charger (5V, 2,3 A).

**Comment by xseignard** [comment]
Could you try the following options?
```
var opts = {
  maxPrintingDots: 10,
  heatingTime: 100,
  heatingInterval: 3,
  commandDelay: 3
};
```

**Comment by clem91** [comment]
I will try the options as soon as I have new paper rolls =). I keep you in touch

**Comment by xseignard** [comment]
:) you can find paper rolls in plain stationery stores (en français: papeterie)

**Comment by clem91** [comment]
Hey there ! 

It works like a charm i had to play with the options you gave me. It's not really the same as you gave it but with some (weak word) printings I managed to have a pretty good images printed. Thank you @xseignard

**Comment by xseignard** [comment]
@clem91 could you please share the options that solve your problem? It will improve the documentation.

And congrats! Hve fun!

**Comment by clem91** [comment]
Here the information:

Adafruit mini printer
5V 2Ah power supply
and here the combination of printing options : 

```
const opts = {
  maxPrintingDots: 6,
  heatingTime: 50,
  heatingInterval: 4,
  commandDelay: 4
};
```

**Comment by xseignard** [comment]
True that.

I also noticed these printers work better with 9v power supply.

Have fun.

Regards
