### ISSUE TITLE
Strange characters printed 

### ISSUE THREAD

**Issue by FMRiggio** [xseignard/thermalPrinter#25]
Hi, I'm using this printer : https://www.adafruit.com/product/600 
With Arduino it works fine, but I’m trying to make it works with a USB to TTL chip with this (https://www.amazon.it/PIXNOR-FT232RL-adattatore-seriale-Arduino/dp/B013QRUA6W/) . The issue is that when I run the demo, I got a series of strange characters instead of the text.
I've tried to change the charset, but it didn't change.
Can you help me?
Thanks.
Filippo

**Comment by xseignard** [comment]
Please show me some code.
Also what are the opts you use when creating a thermal printer instance?

Are you sure your usb to ttl works?

What is the characteristics of your power supply?

Regards

**Comment by FMRiggio** [comment]
`
var Printer = require('thermalprinter');
var SerialPort = require('serialport');
var sPort = new SerialPort('/dev/ttyUSB0', {
	baudrate: 19200,
	autoOpen: false
});


sPort.open(function (err) {
	if (err) {
		return console.log('Error opening port: ', err.message);
	}
});


sPort.on('open',function() {
	var printer = new Printer(sPort);

	printer.on('ready', function() {
		console.log('printer ready');

		printer
			.indent(10)
			.horizontalLine(16)
			//.bold(true)
			.indent(10)
			.printLine('first line')
			//.bold(false)
			//.inverse(true)
			//.big(true)
			//.right()
			//.printLine('second line')
			.print(function() {
				console.log('done');
				process.exit();
			});
	});
});`

The options are the default one.
The power is a standard power supply 5V - 2A.
I think it could be the usb to ttl. Which one have you used?

Thanks

**Comment by xseignard** [comment]
Can you try the following printing options?

```
var opts = {
  maxPrintingDots: 10,
  heatingTime: 100,
  heatingInterval: 3,
  commandDelay: 3
};
```

Regarding my usb to ttl, I cannot remember from where I got it.

Regards

**Comment by FMRiggio** [comment]
Hi, I've tryied that settings, but it doesn't work either. Same result as before.
Thanks

**Comment by xseignard** [comment]
Well, it seems that your power supply and/or your usb to ttl cable are in trouble

Regards

**Comment by FMRiggio** [comment]
Hi @xseignard , I found the error, it's in the example. 
**baudrate** should be camelCase: **baudRate**

Thanks for your time.
Filippo

**Comment by xseignard** [comment]
OH! I think they changed from baudrate to baudRate in node-serialport!

Nice catch @FMRiggio ! If you want to make a pull request to change the docs + examples, it is more than welcome :)
