### ISSUE TITLE
Not an issue, a question I suppose!

### ISSUE THREAD

**Issue by colinta** [xseignard/thermalPrinter#5]
I'll have a chance soon to test this out myself, but I was wondering if you've tried using this from a raspberry pi, using the port `/dev/ttyAMA0`?

**Comment by xseignard** [comment]
Hello @colinta 

It should work, provided you declare the right serial port

```
var SerialPort = require('serialport').SerialPort,
    serialPort = new SerialPort('/dev/ttyAMA0', {
        baudrate: 19200
    }),
    Printer = require('thermalprinter');
```

Nothing else, but please confirm!

**Comment by colinta** [comment]
Yup, that's what I was hoping!  I'll let you know.

**Comment by xseignard** [comment]
So what fancy things are you doing with your printer?

**Comment by colinta** [comment]
I've got a wifi adapter plugged in, and I'm using Firebase to monitor print jobs, and scheduling things like "print the weather at 7am every morning".  I wrote an iOS app that can queue jobs (again, to Firebase), so I can print todo/shopping lists.  This is all a birthday present for my brother (his idea!).

**Comment by xseignard** [comment]
Nice!
Is the wifi adapter directly plugged to the printer so you got a wireless printer??
If so, I would be glad to see such setup!

Regards

**Comment by colinta** [comment]
It's plugged into the raspberry pi - but yes, it's a wireless printer! :-D

I'll post the code soon.

**Comment by colinta** [comment]
So far I'm stuck on an error from `bindings`

```
Error: Could not locate the bindings file. Tried:
 → /home/pi/printy-thingy/node_modules/thermalprinter/node_modules/deasync/build/deasync.node
 → /home/pi/printy-thingy/node_modules/thermalprinter/node_modules/deasync/build/Debug/deasync.node
 → /home/pi/printy-thingy/node_modules/thermalprinter/node_modules/deasync/build/Release/deasync.node
 → /home/pi/printy-thingy/node_modules/thermalprinter/node_modules/deasync/out/Debug/deasync.node
 → /home/pi/printy-thingy/node_modules/thermalprinter/node_modules/deasync/Debug/deasync.node
 → /home/pi/printy-thingy/node_modules/thermalprinter/node_modules/deasync/out/Release/deasync.node
 → /home/pi/printy-thingy/node_modules/thermalprinter/node_modules/deasync/Release/deasync.node
 → /home/pi/printy-thingy/node_modules/thermalprinter/node_modules/deasync/build/default/deasync.node
 → /home/pi/printy-thingy/node_modules/thermalprinter/node_modules/deasync/compiled/0.12.0/linux/arm/deasync.node
    at bindings (/home/pi/printy-thingy/node_modules/thermalprinter/node_modules/deasync/node_modules/bindings/bindings.js:88:9)
```

**Comment by xseignard** [comment]
That's weird

What's your node version?

**Comment by colinta** [comment]
I reinstalled node, hoping that would help.  I think it's version 0.12.0 now.

**Comment by xseignard** [comment]
So I tried on a RPI (i don't have a printer right now)

try this
```
cp /home/pi/printy-thingy/node_modules/thermalprinter/node_modules/deasync/bin/linux-arm-node-0.12/deasync.node /home/pi/printy-thingy/node_modules/thermalprinter/node_modules/deasync/build/deasync.node
```

If this work it is definitely a `deasync` bug.

Regards,

Xavier

**Comment by colinta** [comment]
Awesome, thanks!  I'll try that tonight.

**Comment by colinta** [comment]
I didn't see that file, so I copied one of the `linux` nodes, but none of them worked :-(

**Comment by xseignard** [comment]
That weird because I see it on my PI?? Maybe you should ask on the deasync repo.

**Comment by colinta** [comment]
Oh that IS weird... I'll see what I can get over there.  Thanks for the help!
