### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by zaccolley** [xseignard/thermalPrinter#6]
Printer uses a version of ASCII ( ASCII, GB2312-80(Chinese)? ) and when you try to print characters such as the box drawing chars it encodes wrong.

e.g ┼╞╟╚╔╩╦╠═╬╧╨╤╥

[I solved this in my code](https://github.com/zaccolley/tessel-thermalprinter/blob/master/index.js#L206) but I feel like I'm going about it the complete wrong way, is there a better solution?

**Comment by xseignard** [comment]
AFAIK you can configure the charset the printer uses.
Check this http://www.adafruit.com/datasheets/A2-user%20manual.pdf (chapter Select an internal character set p.15/16)

Maybe it will fix your issue? This functionality can be added to the lib.

Please note that I don't have any printer to test for the next 2 weeks, I'll try some tests when I come home.

Regards,

Xavier

**Comment by xseignard** [comment]
Still not back home, any updates here? /cc @zaccolley

**Comment by xseignard** [comment]
I close it for now, feel free to reopen if needed.

Regards

**Comment by xseignard** [comment]
I reopen it since I'm facing the issue.
@zaccolley I checked your code, but it doesn't feel OK for me, I'm trying to implement a solution with autoswitching charsets if the char you need to print is not in the current charset.

I will push it today, and I would like you to review it if you're OK.

Regards

**Comment by xseignard** [comment]
Hi @zaccolley 
I updated the lib to version 0.3.1.

Could you please have a look here: https://github.com/xseignard/thermalPrinter/blob/master/src/printer.js#L222-L252

With my printer I cannot access the codes you used, it only prints chinese chars, any idea?

**Comment by xseignard** [comment]
v0.3.5 of the lib should close it
I used your idea
regards
